### ISSUE TITLE
KITSUNE is not working

### ISSUE THREAD

**Issue by yh1126611** [natapol/kitsune#8]
When I try to run ` kitsune cre` it will never end. I know it takes long for large genomes, but after 24 hours, it is still at 0%.

When I run the provided example command with the example files, I get:
`OSError: [Errno 24] Too many open files`

**Comment by dacheampong** [comment]
Hello, thanks for your interest in Kitsune, I'm trying to reproduce the error at my end. Could you share the command you using and the python version. Kitsune cre works on a single genome at a time.
